### PR TITLE
Implemented CRUD operations for products in Django:

### PR DESCRIPTION
**Pull request by natischmidt**
- Added views for listing, viewing details, creating, updating, and deleting products.
- Ensured proper form handling and redirection in create and update views.
- Integrated product management functionality seamlessly with existing Django project.

### CODE REVIEW

**Comment by jani-at-noq** [comment]
I think we should add some validation for the data. Host should be existing host and type can only be room or woman-only.

**Comment by natischmidt** [comment]
> I think we should add some validation for the data. Host should be existing host and type can only be room or woman-only.

u can already only chose existing hosts, ive added the type so it can only be one of those two.

**Comment by jani-at-noq** [comment]
Ser bra ut. En liten sak du ska kolla är input för room:
if product_type not in ['room', 'woman-only']:

Vad händer om man matar in Room eller Woman-Only? Ska man ha funktion som konverterar väder till lower case?

Om det är inte problem är allt annat ok tänker jag.

**Review by jani-at-noq — APPROVED** [review]
Looks good.

**Pull request merged**
