### PR TITLE
Added first_name and last_name to UserSchema and LoginSchema in api_s…

### PR DESCRIPTION
**Pull request by MarioDanilo0111**
…chemas.py, updated api.py to return these fields, and added tests to test_user_api.py

- Updated UserSchema in api_schemas.py to include first_name and last_name fields.
- Updated LoginSchema in api_schemas.py to include first_name and last_name for login response.
- Modified api.py to return first_name and last_name in the login API response.
- Added unit test in test_user_api.py to verify first_name and last_name are returned correctly after login.

### CODE REVIEW

**Review by jani-at-noq — CHANGES_REQUESTED** [review]
We should also do changes to the generate_data script. All users in the test data are missing the first name and last name at the moment. So if you call this API we return empty strings locally.

**Review by natischmidt — CHANGES_REQUESTED** [review]
check noq_django/backend/scripts/generate_data.py because its giving password as clear text error

**Comment by jani-at-noq** [comment]
> check noq_django/backend/scripts/generate_data.py because its giving password as clear text error

I don’t think it matters. We write the password in the readme file for frontend anyway.

**Review by jani-at-noq — APPROVED** [review]
Looks good. There is error from the test that Nati pointed out. That should be solved, but the solution can be to exclude generate_data file if possible.

**Review by tobbe-joh — APPROVED** [review]

**Comment by jani-at-noq** [comment]
> > check noq_django/backend/scripts/generate_data.py because its giving password as clear text error
> 
> I don’t think it matters. We write the password in the readme file for frontend anyway. Can we add exception for this file?

image

**Review by jani-at-noq — APPROVED** [review]

**Review by natischmidt — APPROVED** [review]

**Pull request merged**
